import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex space-x-8 min-h-screen">
          <Sidebar />
          <div className="w-[1px] bg-zinc-600 mt-8" />
          <div className="p-8 flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
